name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/puncak_natas_angin_pegunungan_muria_kabupaten_kudus_1.jpeg
  - assets/images/pngwing_1.png
  - assets/images/karimunjawa_1692.jpeg
  - assets/images/pantai_kartini_1248_x_70312.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/pngwing_1.png
  - assets/images/ellipse_2.jpeg
  - assets/images/karimunjawa_1692.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/images/karimunjawa_1692.jpeg
  - assets/images/pngwing_1.png
  - assets/images/pantai_kartini_1248_x_70312.jpeg
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown
  - assets/vectors/Unknown

